from enum import Enum

class DatabaseEnums(Enum):

    
    PROJECT_COLLECTION_NAME="PROJECT_COLLECTION"
    CHUNK_COLLECTION_NAME= "CHUNK_COLLECTION"
    ASSET_COLLECTION_NAME= "ASSETS_COLLECTION"
    
    
    
